import { type NextPage } from "next";
import Head from "next/head";
import Header from "./components/Header";
import Experiments from "./components/Experiments";
import Volunteering from "./components/Volunteering";
import RecentWork from "./components/RecentWork";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Portfolio</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen bg-[#333333] text-white">
                <div className="max-w-[60rem] px-6 py-5 md:p-12 mx-auto">
                    <Header />
                    <RecentWork />
                    <Experiments />
                    <Experiments />
                    <Experiments />
                    <Volunteering />
                </div>
            </main>
        </>
    );
};

export default Home;
