/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import Head from "next/head";
import Header from "../components/organisms/Header";
import Experiments from "../components/organisms/Experiments";
import Volunteering from "../components/organisms/Volunteering";
import RecentWork from "../components/organisms/RecentWork";
import Words from "~/components/organisms/Words";
import { PrismaClient } from '@prisma/client';

import type { Article } from "./blog/[slug]";

const prisma = new PrismaClient();

const Home = ({ articles }: {articles: Article[]}) => {
    return (
        <>
            <Head>
                <title>Portfolio</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="min-h-screen bg-white text-designColor">
                <div className="max-w-[60rem] px-6 py-5 md:p-12 mx-auto">
                    <Header />
                    <RecentWork />
                    <Experiments />
                    <Words articles={articles} />
                    <Volunteering />
                </div>
            </div>
        </>
    );
};

export async function getStaticProps() {
    const articles = await prisma.article.findMany({
      include: { contentElements: true },
    });

    return { props: { articles: JSON.parse(JSON.stringify(articles)) }, revalidate: 1 };
}

export default Home;
