import { type NextPage } from "next";
import Head from "next/head";
import Header from "../components/organisms/Header";
import Experiments from "../components/organisms/Experiments";
import Volunteering from "../components/organisms/Volunteering";
import RecentWork from "../components/organisms/RecentWork";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Portfolio</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="min-h-screen bg-white text-designColor">
                <div className="max-w-[60rem] px-6 py-5 md:p-12 mx-auto">
                    <Header />
                    <RecentWork />
                    <Experiments />
                    <Experiments />
                    <Experiments />
                    <Volunteering />
                </div>
            </div>
        </>
    );
};

export default Home;
